apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "kube-admission.fullname" . }}-nginx-configuration
  labels:
    {{- include "kube-admission.labels" . | nindent 4 }}
data:
  conf.d-default.conf: |
    server {
        listen 443 ssl;
        server_name  _;

        ssl_certificate /etc/nginx/certs/tls.crt;
        ssl_certificate_key /etc/nginx/certs/tls.key;

        #charset koi8-r;
        #access_log  /var/log/nginx/host.access.log  main;

        location / {
            proxy_pass http://127.0.0.1:{{ .Values.container.httpPort }};
        }
    }