apiVersion: v1
kind: Service
metadata:
  name: {{ include "kube-admission.fullname" . }}
  labels:
    {{- include "kube-admission.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 443
      targetPort: https
      protocol: TCP
      name: https
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "kube-admission.selectorLabels" . | nindent 4 }}
